# Generated by Django 3.0.3 on 2020-03-30 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Solicita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('origem', models.CharField(blank=True, max_length=128, null=True, verbose_name='Origem')),
                ('destino', models.CharField(blank=True, max_length=128, null=True, verbose_name='Destino')),
                ('Solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_solicitacao.Pessoa')),
            ],
            options={
                'verbose_name': 'Solicitar Transporte',
                'verbose_name_plural': 'Solicitar Transportes',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nome')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_solicitacao.Pessoa')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Atende',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_solicitacao.Pessoa')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_solicitacao.Carro')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_solicitacao.Solicita')),
            ],
            options={
                'verbose_name': 'Atender Solicitação',
                'verbose_name_plural': 'Atender Solicitações',
            },
        ),
    ]
